from typing import Dict, List

# Source Identifiers
SOURCE_TAVILY = "tavily"

# Domain Lists
BLOCKLIST_DOMAINS: List[str] = [
    "linkedin.com/jobs",
    "indeed.com",
    "careerjet",
    "workopolis",
    "jooble",
    "glassdoor",
    "himalayas",
    "drjobpro",
    "remoteok",
    "remotive",
    "ziprecruiter",
    "simplyhired",
    "craigslist",
    "snagajob",
    "monster",
    "talent.com",
    "neuvoo",
    "adzuna",
    "getwork",
    "lensa",
    "jobrapido",
    "jobstreet",
    "seek.com",
    "flexjobs",
    "wellfound",
    "builtin",
    "dice.com",
    "stackoverflow.com/jobs",
    "hired.com",
    "angel.co",
    "weworkremotely",
    "jobgether",
    "jobicy",
    "remote.co",
    "nodesk",
    "jobspresso",
    "working-nomads",
    "pangian",
    "remoters",
    "findwork",
    "authenticjobs",
    "landing.jobs",
    "startup.jobs",
    "workingnomads",
]

WHITELIST_DOMAINS: List[str] = [
    ".gc.ca",
    ".canada.ca",
    "jobbank.gc.ca",
    "jobs.gc.ca",
    ".gov.on.ca",
    ".gov.bc.ca",
    ".gov.ab.ca",
    ".gouv.qc.ca",
    "amazon.jobs",
    "careers.google.com",
    "microsoft.com/careers",
    "apple.com/careers",
    "meta.com/careers",
    "nvidia.com/careers",
    "shopify.com/careers",
    "rbc.com/careers",
    "td.com/careers",
    "scotiabank.com/careers",
    "bmo.com/careers",
    "cibc.com/careers",
    "deloitte.com/careers",
    "pwc.com/careers",
    "ey.com/careers",
    "kpmg.com/careers",
    "mckinsey.com/careers",
    "bcg.com/careers",
    "accenture.com/careers",
    "ibm.com/careers",
    "salesforce.com/careers",
    "oracle.com/careers",
    "sap.com/careers",
    "cisco.com/careers",
    "intel.com/careers",
    "amd.com/careers",
    "dell.com/careers",
    "hp.com/careers",
    "workday.com/careers",
    "servicenow.com/careers",
    "atlassian.com/careers",
    "stripe.com/jobs",
    "openai.com/careers",
    "anthropic.com/careers",
    "cohere.com/careers",
    "aircanada.com/careers",
    "westjet.com/careers",
    "telus.com/careers",
    "bell.ca/careers",
    "rogers.com/careers",
    "loblaw.ca/careers",
    "costco.com/careers",
    "walmart.ca/careers",
    "greenhouse.io",
    "lever.co",
    "workable.com",
    "ashbyhq.com",
    "jobs.lever.co",
    "boards.greenhouse.io",
]

# Filtering Keywords
JOB_URL_KEYWORDS: List[str] = [
    "/jobs",
    "/job",
    "careers",
    "career",
    "opening",
    "openings",
    "position",
    "positions",
    "vacancy",
    "apply",
    "hiring",
    "recruitment",
    "opportunities",
    "join-us",
    "join-our-team",
    "work-with-us",
]

CANADA_HINTS: List[str] = [
    "canada",
    "ontario",
    "quebec",
    "alberta",
    "british columbia",
    "manitoba",
    "saskatchewan",
    "nova scotia",
    "new brunswick",
    "newfoundland",
    "labrador",
    "prince edward island",
    "pei",
    "northwest territories",
    "nunavut",
    "yukon",
    "toronto",
    "vancouver",
    "montreal",
    "ottawa",
    "calgary",
    "edmonton",
    "winnipeg",
]

# Classification Keywords
SKILL_KEYWORDS: Dict[str, str] = {
    "python": "Python",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "go": "Go",
    "golang": "Go",
    "java": "Java",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "aws": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "terraform": "Terraform",
    "react": "React",
    "node": "Node.js",
    "node.js": "Node.js",
    "ml": "Machine Learning",
    "machine learning": "Machine Learning",
    "data": "Data",
    "security": "Security",
    "devops": "DevOps",
    "cloud": "Cloud",
}

INNOVATION_KEYWORDS: Dict[str, str] = {
    "genai": "GenAI",
    "generative ai": "GenAI",
    "llm": "LLM",
    "ai": "AI",
    "machine learning": "Machine Learning",
    "robot": "Robotics",
    "robotics": "Robotics",
    "autonomous": "Autonomous Systems",
    "quantum": "Quantum",
    "biotech": "Biotech",
    "bioinformatics": "Bioinformatics",
    "ar": "AR/VR",
    "vr": "AR/VR",
    "augmented reality": "AR/VR",
    "virtual reality": "AR/VR",
    "cybersecurity": "Cybersecurity",
    "security": "Cybersecurity",
    "energy": "Clean Energy",
    "climate": "Climate Tech",
    "blockchain": "Web3",
    "web3": "Web3",
}

WEIRD_KEYWORDS: Dict[str, str] = {
    "prompt engineer": "Prompt Engineering",
    "futurist": "Futurist",
    "quantum": "Quantum",
    "bioinformatics": "Bioinformatics",
    "ethicist": "AI Ethics",
    "responsible ai": "AI Ethics",
    "cryptographer": "Cryptography",
    "threat hunter": "Threat Hunter",
    "astrophys": "Astrophysics",
    "geospatial": "Geospatial",
    "metaverse": "Metaverse",
    "behavioral": "Behavioral Science",
    "neuroscience": "Neuroscience",
    "policy": "Policy",
    "regulatory": "Regulatory",
}

# Search Defaults
TAVILY_DEFAULT_QUERIES: str = (
    'site:gc.ca "job posting" Canada;'
    'site:canada.ca "job posting" Canada;'
    'site:jobbank.gc.ca "job posting";'
    'site:jobs.gc.ca "job posting";'
    'Canada "job posting" "apply"'
)
